config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'my_drones', to: 'drones#my_drones'
  get 'my_drones/:id/edit', to: 'drones#edit', as: "editmydrone"
  post '/drones/:id/edit/change', to: 'drones#change', as: "dronechange"
  resources :drones do
    resources :bookings, only: [:index, :show, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :drone
  belongs_to :user

  validates :days, presence: true, numericality: { only_integer: true }
end

app/models/drone.rb
class Drone < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :owner, foreign_key: :user_id,  class_name: "User"

  mount_uploader :photo, PhotoUploader



  validates :name, presence: true
  validates :brand, presence: true
  validates :autonomy, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @booking = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @drone = Drone.find(params[:drone_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.drone = @drone

    if @booking.save
      redirect_to @drone
    else
      render 'drone/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:days)
  end
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @drones = Drone.all

    @markers = @drones.map do |drone|
      {
        lat: drone.latitude,
        lng: drone.longitude,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def new
    @drone = Drone.new
  end

  def create
    @drone = Drone.new(drone_params)
    @drone.owner = current_user

    if @drone.save
      redirect_to drone_path(@drone)
    else
      render :new
    end
  end

  def show
    @drone = Drone.find(params[:id])
  end

  def edit
    @drone = Drone.find(params[:id])
    # @my_drones = Drone.where(owner: current_user.id)
  end

  def update
    # @my_drones = Drone.where(owner: current_user.id)
    # @my_drones.update(drone_params)
        # @my_drones.update(drone_params)
    @drone = Drone.find(params[:id])
    @drone.update(drone_params)
    redirect_to my_drones_path
  end

  def destroy
    @drone = Drone.find(params[:id])
    @drone.destroy
    redirect_to my_drones_path
  end

  def my_drones
    @my_drones = Drone.where(owner: current_user.id)
  end

  def change
    @drone = Drone.find(params[:id])
    @drone.available = !@drone.available
    @drone.save
    redirect_to @drone
  end

   private

  def drone_params
    params.require(:drone).permit(:name, :brand, :autonomy, :price, :video, :available, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @drones = Drone.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drones/edit.html.erb
<div class="vertically-align">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <div class="form-design">
        <h2>Edit you drone</h2>

        <%= simple_form_for @drone do |f| %>
          <%= f.input :name, value: "#{@drone.name}", label: "Your drone's name", error: "Drone's name is mandatory, please specify one" %>
          <%= f.input :brand, value: "#{@drone.brand}", label: 'Brand', error: "Brand is mandatory, please specify one" %>
          <%= f.input :autonomy, value: "#{@drone.autonomy}", label: 'Autonomy', error: "Autonomy is mandatory, please specify one" %>
          <%= f.input :price, value: "#{@drone.price}", label: 'Price', error: "Price is mandatory, please specify one" %>
          <%= f.button :submit, "Edit", class: "btn-primary" %>
        <% end %>

        <p>Your drone is :
          <% if @drone.available == true %>
            Available
          <% else %>
            Unavailable
          <% end %>
          <%= link_to "Change", dronechange_path(@drone), method: :post %>
        </p>
        <%= link_to "Back to the drones'list" ,root_path  %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/drones/my_drones.html.erb
<div class="container">
  <h3 class="index-title">My Drones</h3>
    <% @my_drones.each do |my_drone| %>
    <div class="row row-eq-height drone-index">
        <div class="col-xs-12 col-md-4 left-pad">
          <%= cl_image_tag my_drone.photo, height: 270, width: 360, crop: :fill, class: "my-drone-image" %>
        </div>
        <div class="col-xs-12 col-md-6 my-drone-details text-col">
          <div class="col-xs-12 col-md-3">
            <h4 class="drone-keys">Name: </h4>
            <h4 class="drone-keys">Brand: </h4>
            <h4 class="drone-keys">Battery life: </h4>
            <h4 class="drone-keys">Video specs: </h4>
          </div>
          <div class="col-xs-12 col-md-3">
            <h4 class="my-title"><%= my_drone.name %></h4>
            <h4><%= my_drone.brand %></h4>
            <h4><%= my_drone.autonomy %></h4>
            <h4><%= my_drone.video %></h4>
          </div>
          <div class="col-xs-12 col-md-3">
            <h4 class="drone-keys">Lender: </h4>
            <h4 class="drone-keys">From: </h4>
            <h4 class="drone-keys">To: </h4>
          </div>
          <div class="col-xs-12 col-md-3">
            <h4 class="my-title">Nayeli</h4>
            <h4>26/05/2018</h4>
            <h4>28/05/2018</h4>
          </div>
        </div>
    <div class="col-xs-12 col-md-2 drone-price">
      <div class="delete-edit">
        <%= link_to '<i class="far fa-edit" style="font-size:26px;"></i>'.html_safe, editmydrone_path(my_drone), class: "edit-margin" %>
        <%= link_to '<i class="far fa-times-circle" style="font-size:26px;"></i>'.html_safe, drone_path(my_drone), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
      <div class="pricing">
        <h3>$<%= my_drone.price %><span class="pd"> per day</span></h3>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/drones/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-design">
        <h2>Add your drone</h2>

        <%= simple_form_for @drone do |f| %>
          <%= f.input :name, label: "Your drone's name", error: "Drone's name is mandatory, please specify one" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.input :brand, label: 'Brand', error: "Brand is mandatory, please specify one" %>
          <%= f.input :autonomy, label: 'Battery life', error: "Battery life is mandatory, please specify one" %>
          <%= f.input :video, label: 'Video resolution', error: "Video resolution is mandatory, please specify one" %>
          <%= f.input :price, label: 'Price', error: "Price is mandatory, please specify one" %>
          <%= f.input :available, label: 'Available Now ?' %>
          <%= f.button :submit, "Add drone", class: "btn-primary" %>
        <% end %>

        <%= link_to "Back to the drones'list" , root_path  %>
      </div>
    </div>
  </div>
</div>

app/views/drones/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-1">
        <div class="elements">
          <div class="pic"><%= cl_image_tag @drone.photo, height: 270, width: 360, crop: :fill %></div>
          <div class="elem"><h2><%= @drone.name %></h2></div>
          <div class="elem"><p><%= @drone.brand %></p></div>
          <div class="elem"><p><%= @drone.autonomy %></p></div>
          <div class="elem"><p><%= @drone.price %></p></div>
          <% @drone.bookings.each do |booking| %>
          <%= booking.days %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4 col-md-offset-1">
        <%= simple_form_for([@drone, @booking]) do |f| %>
         <%= f.input :days %>
          <%= f.submit %>
          <% end %>

      </div>
    </div>
</div>
      <%= link_to "Back to the drones'list", root_path  %>

app/views/drones/test.html.erb
<div class="container">
  <h3 class="index-title">My Drones</h3>
  <div class="row row-eq-height">
    <% @my_drones.each do |my_drone| %>
        <div class="card my-drone-list">
          <div class="col-xs-12 col-md-4 left-pad">
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <!-- Carousel indicators -->
                  <ol class="carousel-indicators">
                      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                      <li data-target="#myCarousel" data-slide-to="1"></li>
                      <li data-target="#myCarousel" data-slide-to="2"></li>
                  </ol>
                  <!-- Wrapper for carousel items -->
                  <div class="carousel-inner">
                      <div class="item active">
                          <img src="https://images.unsplash.com/photo-1514043454212-14c181f46583?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=88519aba92b279e4acdacbbd5c9dc98e&auto=format&fit=crop&w=2689&q=80" alt="First Slide">
                      </div>
                      <div class="item">
                          <img src="https://images.unsplash.com/photo-1514043454212-14c181f46583?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=88519aba92b279e4acdacbbd5c9dc98e&auto=format&fit=crop&w=2689&q=80" alt="Second Slide">
                      </div>
                      <div class="item">
                          <img src="https://images.unsplash.com/photo-1514043454212-14c181f46583?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=88519aba92b279e4acdacbbd5c9dc98e&auto=format&fit=crop&w=2689&q=80" alt="Third Slide">
                      </div>
                  </div>
                  <!-- Carousel controls -->
                  <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="carousel-control right" href="#myCarousel" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
              </div>
          </div>
            <div class="col-xs-12 col-md-4">
                <div class="my-drone-info">
                  <h2 class="my-title"><%= my_drone.name %></h2>
                  <h4><%= my_drone.brand %></h4>
                  <p><%= my_drone.autonomy %></p>
                  <p><%= my_drone.video %></p>
                </div>
            </div>
            <div class="col-xs-12 col-md-4">
              <div class=" my-drone-price">
                <h3>$<%= my_drone.price %><span class="pd"> per day</span></h3>
              </div>
            </div>
          </div>
    <% end %>
        </div>
  </div>

</div>

app/views/layouts/_banner.html.erb
<div class="banner">
  <%= video_tag 'banner-video.mp4', autoplay: :autoplay, loop: :loop, mute: :mute %>)
  <div class="banner-content">
    <h1>Sky's the limit</h1>
    <h4>Rent a drone, push your limit</h4>
    <a href="<%= new_user_registration_path %>" class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

<!-- linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), -->

app/views/layouts/_calendar.html.erb
<%= month_calendar do |date| %>
  <%= date.day %>
<% end %>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add drone", new_drone_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My drones", my_drones_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: current_user.user_name) %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-lock"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sky's the limit</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashes' %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
      <%= javascript_pack_tag "map" %>
      <%= javascript_pack_tag 'application' %>
  </body>

</html>

app/views/pages/home.html.erb
<%=  render 'layouts/banner' %>
<div class="container">
  <h3 class="index-title">Drones for rent !</h3>
  <div class="row">

<% @drones.each do |drone| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <div class="hovereffect">
            <%= cl_image_tag drone.photo, height: 270, width: 360, crop: :fill %>
            <div class="overlay">
              <% if drone.available == true %>
                <a class="info available" href=<%= "#{drone_path(drone)}" %>>Available</a>
              <% else drone.available == false %>
                <a class="info unavailable" href=<%= "#{drone_path(drone)}" %>>Unavailable</a>
              <% end %>
            </div>
          </div>
          <article class="info">
            <div class="name">
              <h3><%= drone.name %></h3>
              <p><%= drone.brand %></p>
              <p><%= drone.owner.user_name %></p>
            </div>
            <div class="price">
              <h3>$<%= drone.price %><span class="pd"> per day</span></h3>
            </div>

          </article>
        </div>
      </div>
<% end %>
    </div>
  </div>

  <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>"></div>